### ISSUE TITLE
论文原文及训练问题

### ISSUE THREAD

**Issue by mebius-coder** [h751410234/DATR#1]
您好，请问有论文原文链接吗
以及，这个预训练模型是怎么得到的，只有用这个预训练模型才能复现普通光学图像中的效果吗? 如果我想训练自定义数据集比如光学遥感图像，需要怎么做？
感谢

**Comment by h751410234** [comment]
这个是我整准备投的，论文还没写完，代码先放上来了。&nbsp;
光学遥感图像可以看下我的另一个工作RemoteSensingTeacher：h751410234/RemoteSensingTeacher (github.com)




黑客大狭101
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "h751410234/DATR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月23日(星期二) 晚上10:56
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[h751410234/DATR] 论文原文及训练问题 (Issue #1)





 
您好，请问有论文原文链接吗
 以及，这个预训练模型是怎么得到的，只有用这个预训练模型才能复现普通光学图像中的效果吗? 如果我想训练自定义数据集比如光学遥感图像，需要怎么做？
 感谢

**Comment by mebius-coder** [comment]
牛的，这么早就把代码放出来了，向你致敬。我刚下载了那一篇，这个实验的计算显卡要求什么，单卡3090 24GB可以吗，batch_size和学习率设置为多少呢，我是做光学遥感图像DA的，不过选的数据集不太一样。感谢您的回复，祝高中！

**Comment by h751410234** [comment]
具体超参数的配置文件我github里面有写。单卡3090 24GB显存或许只能在最低batch_size的设置上跑。 由于DETR类的网络 和 域适应任务 都对batch_size的设置比较敏感，所以我不太确定能否跑出比较好的结果。
751410234
***@***.***
---- 回复的原邮件 ----
***@***.***>发送日期2024年4月23日 ***@***.***>***@***.***>,
***@***.***>主题Re: [h751410234/DATR] 论文原文及训练问题 (Issue #1)
牛的，这么早就把代码放出来了，向你致敬。我刚下载了那一篇，这个实验的计算显卡要求什么，单卡3090 24GB可以吗，batch_size和学习率设置为多少呢，我是做光学遥感图像DA的，不过选的数据集不太一样。感谢您的回复，祝高中！
