### ISSUE TITLE
如何使用inference.py

### ISSUE THREAD

**Issue by Cornell-CUG** [h751410234/DATR#12]
https://pan.baidu.com/s/1ZGvYjwXUMoBqtcGHfTnNww?pwd=mxxg，这个是训练好的模型吗，能否用到inference.py中呢

**Comment by h751410234** [comment]
是训练好的，可以进行推理

**Comment by Cornell-CUG** [comment]
> 是训练好的，可以进行推理

<img width="672" alt="44855c10ac0b8c7e4fe74c00ba08435" src="https://github.com/user-attachments/assets/1a3d7128-b8ee-439a-973a-9064ff77ee5d">
请问是使用这个权重参数吗，这个权重参数是完整训练的，还是burn in stage呢

**Comment by h751410234** [comment]
完整训练的

**Comment by Cornell-CUG** [comment]
> 完整训练的

![image](https://github.com/user-attachments/assets/20de4aa9-5e10-4177-a8d3-7e83dc113559)
这是运行DINO_eval.sh,使用cityscpaes-->cityscapes_foggy百度网盘提供的链接下载的权重，感觉不是完整训练的呀

**Comment by h751410234** [comment]
估计是你那边数据集自己制备的？导致类别标号错位了。例如，我这边1对应的类别“车”，你那边可能是其他的标号。我这边数据集使用的是这个https://github.com/chengchunhsu/EveryPixelMatters

**Comment by Cornell-CUG** [comment]
> 估计是你那边数据集自己制备的？导致类别标号错位了。例如，我这边1对应的类别“车”，你那边可能是其他的标号。我这边数据集使用的是这个https://github.com/chengchunhsu/EveryPixelMatters

我使用的是你提供的这个网址下载的标注数据json文件，图像数据来自cityscapes官网

**Comment by h751410234** [comment]
那不应该，有具体到每个类别的精度吗

**Comment by h751410234** [comment]
![image](https://github.com/user-attachments/assets/92efeb90-ec5b-483a-9b50-a47f1afe1dd3)
这个是我这边的顺序

**Comment by Cornell-CUG** [comment]
> ![image](https://private-user-images.githubusercontent.com/46713146/380489996-92efeb90-ec5b-483a-9b50-a47f1afe1dd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMjgyODMsIm5iZiI6MTczMDAyNzk4MywicGF0aCI6Ii80NjcxMzE0Ni8zODA0ODk5OTYtOTJlZmViOTAtZWM1Yi00ODNhLTliNTAtYTQ3ZjFhZmUxZGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDExMTk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYWZkNTJiNGZmMWRmYjczOTc5NzhkNjEzN2IyNjI2NWQ4OTViODM3YjExYTUzMzM3Mjg4NzYyZWY4NDkwYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9q9c599BR7uA5uLAAYTWglvcXlvtv3xIIbcx7pFb9xY) 这个是我这边的顺序

请问您这张图是来自哪个代码呢，我这边尝试查看一下

**Comment by h751410234** [comment]
需要自己改coco的评估文件，百度就有

**Comment by Cornell-CUG** [comment]
![image](https://github.com/user-attachments/assets/bde3b097-475d-41d3-b553-0dffc185cd72)


> ![image](https://private-user-images.githubusercontent.com/46713146/380489996-92efeb90-ec5b-483a-9b50-a47f1afe1dd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMjgyODMsIm5iZiI6MTczMDAyNzk4MywicGF0aCI6Ii80NjcxMzE0Ni8zODA0ODk5OTYtOTJlZmViOTAtZWM1Yi00ODNhLTliNTAtYTQ3ZjFhZmUxZGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDExMTk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYWZkNTJiNGZmMWRmYjczOTc5NzhkNjEzN2IyNjI2NWQ4OTViODM3YjExYTUzMzM3Mjg4NzYyZWY4NDkwYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9q9c599BR7uA5uLAAYTWglvcXlvtv3xIIbcx7pFb9xY) 这个是我这边的顺序

和你这边是一致的

**Comment by h751410234** [comment]
![image](https://github.com/user-attachments/assets/221b25a1-2361-402a-a93f-8db1ab73e24a)
我这边刚下载权重，然后按照readme推理的，并没有发现问题。要不再看看是否配置的正确。

**Comment by Cornell-CUG** [comment]
> ![image](https://private-user-images.githubusercontent.com/46713146/380491222-221b25a1-2361-402a-a93f-8db1ab73e24a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMzE2NzksIm5iZiI6MTczMDAzMTM3OSwicGF0aCI6Ii80NjcxMzE0Ni8zODA0OTEyMjItMjIxYjI1YTEtMjM2MS00MDJhLWE5M2YtOGRiMWFiNzNlMjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDEyMTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZDcxMWMzMjg5ZjZmMWM2YjJkYjNmNTY3MjllZjdmNGMxY2ViYTIwZGY0MmI0NzIzZGYzY2YyNDdiZTI0ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6FjkxAg-vZLLfYEcGKc0Bt2TsG0UJrdYy2xq4Lle8y0) 我这边刚下载权重，然后按照readme推理的，并没有发现问题。要不再看看是否配置的正确。

请问cityscapes foggy数据集是只针对0.02能见度吗

**Comment by Cornell-CUG** [comment]
> 应该是的

训练使用全部能见度，还是只用0.02

**Comment by h751410234** [comment]
0.02吧，我直接下载这个里面，然后使用的https://github.com/chengchunhsu/EveryPixelMatters
