### ISSUE TITLE
EMA模型和普通模型有什么区别

### ISSUE THREAD

**Issue by Cornell-CUG** [h751410234/DATR#13]
请问普通模型和EMA模型有什么区别

**Comment by h751410234** [comment]
没啥区别，就是里面存的字典名称不一样

**Comment by Cornell-CUG** [comment]
> 没啥区别，就是里面存的字典名称不一样
inference.py和inference_ema_model.py以及teacher_main.py和main.py也没区别吗

**Comment by h751410234** [comment]
（1）main.py是用于第一阶段的脚本，teacher_main.py是用第二阶段自训练的脚本。
（2）inference.py用于推理普通模型的，inference_ema_model.py用于推理教师模型的。

**Comment by h751410234** [comment]
由于普通模型和ema模型在参数存储时的key不一样，因此分了脚本，方便使用。

**Comment by Cornell-CUG** [comment]
> 由于普通模型和ema模型在参数存储时的key不一样，因此分了脚本，方便使用。

感谢您的解答，请问百度网盘中提供的权重是针对哪个完全训练的模型呢

**Comment by h751410234** [comment]
都是和表格精度相符的

**Comment by Cornell-CUG** [comment]
> 都是和表格精度相符的

请问百度网盘的模型权重是教师模型还是学生模型，应该用哪个.sh去eval呢

**Comment by h751410234** [comment]
看名字吧，没带ema的就是普通模型
