### ISSUE TITLE
教师模型是否使用了CPA和DAS模块

### ISSUE THREAD

**Issue by Cornell-CUG** [h751410234/DATR#16]
请问在教师模型中有使用CPA和DAS模块吗，我看代码里好像没有这个过程，但是论文的框图里描述了这个过程

**Comment by h751410234** [comment]
在第一阶段和第二阶段训练的时候，都启用了CPA和DAS模块。 没太懂教师模型使用CPA和DAS的含义，具体的教师模型仅用于提供伪标签，不参与训练，其参数由学生模型通过ema集成得到，学生模型是全程使用CPA和DAS的。
