### ISSUE TITLE
torch.distributed.barrier() 卡住了

### ISSUE THREAD

**Issue by Cornell-CUG** [h751410234/DATR#17]
请问在misc.py文件中，print("Before torch.distributed.barrier()")
    torch.distributed.barrier()
    print("End torch.distributed.barrier()")，多卡训练时卡在这里一直动不了，有时候也会卡在evaluate，也没有报错是什么情况呢，单卡可以正常训练

**Comment by h751410234** [comment]
没遇见过，misc.py这个脚本应该是DINO官方的，我应该没动过。
