### ISSUE TITLE
遥感数据集实验复现指标

### ISSUE THREAD

**Issue by mebius-coder** [h751410234/DATR#18]
您好，请问您有做过光学遥感图像的该工作的实验吗？我基于DATR在遥感数据集做了UCASAOD->CARPK的自适应实验，我的配置是RTX 3090(24G)*2，和A6000相当。batch size=2,其余设置与Sim10k2Cityscapes相同，最高AP如下，
 
![image](https://github.com/user-attachments/assets/a7a7d222-31d3-4b52-b8ac-a798d4f85650)
看起来没有Remote sensing teacher高?

**Comment by G-200010** [comment]
@mebius-coder 您好，您在复现遥感这组实验的时候第一阶段后半部分有出现map50急剧下降的现象吗
