### ISSUE TITLE
第二阶段训练，加载模型问题

### ISSUE THREAD

**Issue by Dr-Zhuang** [h751410234/DATR#2]
使用单卡训练，第一阶段结束，在第二阶段训练时，报错如下：
Traceback (most recent call last):
  File "/media/zh/code/DATR/main_teacher.py", line 565, in <module>
    main(args)
  File "/media/zh/code/DATR/main_teacher.py", line 234, in main
    model_without_ddp.load_state_dict(checkpoint['ema_model'])
KeyError: 'ema_model'

是加载的模型不对么？

**Comment by Dr-Zhuang** [comment]
检查了下，加载的模型需要修改下：
output_dir = Path(args.output_dir)
    if os.path.exists(os.path.join(args.output_dir, 'checkpoint.pth')):
        args.resume = os.path.join(args.output_dir, 'checkpoint.pth')

checkpoint.pth 修改为best_ema_teacher.pth

**Comment by h751410234** [comment]
我当时设置第二阶段训练的时候是新建一个文件夹，然后把第一阶段的模型复制过去。
你这边应该是直接沿用第一阶段训练的文件夹的路径了

**Comment by Dr-Zhuang** [comment]
我后来也是新建的文件夹，args.resume = os.path.join(args.output_dir, 'checkpoint.pth') 加载模型修改为best_ema_teacher.pth就没问题了。
谢谢回复，训练没有问题。
