### ISSUE TITLE
类别可视化的问题

### ISSUE THREAD

**Issue by ZFU123456** [h751410234/DATR#20]
您是否可以把这个可视化的代码公开呢？您可视化后的特征是经过匈牙利匹配算法之后的  还是经过伪标签处理后的特征呢？

**Comment by h751410234** [comment]
我应该是直接可视化的全部obecjt query特征。

**Comment by h751410234** [comment]
我有点记不太清楚了，应该是可视化的object query特征，忘记卡没卡阈值了。
