### ISSUE TITLE
模型训练

### ISSUE THREAD

**Issue by G-200010** [h751410234/DATR#3]
您好 请问这个模型选择单卡训练batchsize为2 在cityscapes到foggycityscapes上训练 效果保持稳健吗

**Comment by h751410234** [comment]
偏差肯定是有的，我之气那尝试锁住随机种子，但应该不太行。精度应该偏差不会太大_，你可以试一下50以上应该没啥问题

**Comment by h751410234** [comment]
偏差肯定是有的，我之前尝试锁住随机种子，但DETR架构应该锁不住。精度应该偏差不会太大，你可以试一下51以上应该没啥问题

**Comment by h751410234** [comment]
偏差肯定是有的，我之前尝试锁住随机种子，但DETR架构应该锁不住。精度应该偏差不会太大，你可以试一下。

**Comment by G-200010** [comment]
好的 谢谢您的回复 我后面会尝试复现您的工作的

**Comment by Cornell-CUG** [comment]
请问怎么多卡训练呢，我三卡，设置bs=3，显示cuda out of memory，但是单卡bs=1可以运行
