### ISSUE TITLE
显存

### ISSUE THREAD

**Issue by G-200010** [h751410234/DATR#5]
您好 我现在是用A6000进行的训练 训练配置和您推荐的一样 但目前面临一个问题 无论是当前DATR的工作 还是您前一篇工作RemoteSensingTeacher 都存在显存占用过高的问题 就是随着训练的不断进行 显存占用在不断增加 最后会因为显存超出而出现core dump 导致训练终止 您有遇到过这两个问题吗 请问针对这一问题 您有什么建议吗 比如第一张图是训练RST时最后一轮显存超了 第二张图DATR刚开始训练 显存占用就达到38000MB左右了
![rst](https://github.com/h751410234/DATR/assets/172945648/16be8f72-1556-411b-8b9a-0d19f0cc5a86)
![DATR](https://github.com/h751410234/DATR/assets/172945648/ff9d5cb9-ed72-4a94-bde8-3b7854f62d1a)

**Comment by h751410234** [comment]
（1）我这边没有考虑过显存的问题，感觉也不太好解决

**Comment by h751410234** [comment]
我这边也是A6000,49G显存。我单卡在遥感场景下训练并没有超显存的现象，不知道你那边是个啥情况。core dump的问题，我不太确定是由于超显存导致的吗，超显存一般不是直接会报out of memory？

**Comment by G-200010** [comment]
那您当时训练的时候有显存占用不断上涨的情况吗 我这边是一直上涨 快满的时候会瞬间减小到较小的数值 然后继续上涨 浮动巨大 有时上涨过高后就会报错 您有什么处理建议吗

**Comment by h751410234** [comment]
显存会不断变换，理论上你这边和我一样的显卡不会出现超显存的问题才对。会不会是硬件出现问题？练其他的网络会出现这种情况吗

**Comment by G-200010** [comment]
谢谢您的回答 我目前也在排查硬件问题 这块显卡整体配置是这两天刚申请到的 目前只跑了您的两篇工作
