### ISSUE TITLE
the shape about output_source？in dino.py

### ISSUE THREAD

**Issue by Bradly-s** [h751410234/DATR#6]
Hello, your job is very good! I have some questions in dino.py:
Is the shape of the output_source [bs,N,256] ?
What is the meaning of N ?

#Second.==============objcet query Prototypical Contrast Adaptation======================
#---- For Source Domain
# 1.--------提取原型特征-----------------
# (1)得到最后一层object query 结果
output_source = hs[-1][:,dn_meta['pad_size']:,:]   #source_query_feature :[bs,N,256]

**Comment by h751410234** [comment]
My impression is that N represents the number of object queries, and the default configuration is 900, which is consistent with the official DINO.
