### ISSUE TITLE
复现过程中遇到问题

### ISSUE THREAD

**Issue by zzk-nb** [h751410234/DATR#9]
![图片1](https://github.com/user-attachments/assets/fe947800-ff9f-4dc0-abce-a5ca6d7e258e)
您好，我在复现过程中一直遇到这个问题，想问一下这是因为数据集的原因吗？

**Comment by h751410234** [comment]
报错没有截全，可以检查下数据集类别和config配置文件设置的是否一致。 DINO配置文件有两个位置（num_classes和dn_labelbook_size）和类别有关。
